stages:
  - test
  - build
  - publish

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"

before_script:
  - git config --global --add safe.directory "$CI_PROJECT_DIR"

test:
  stage: test
  image: rust:1.76-bullseye
  script:
    - cargo test

rustdoc:
  stage: build
  image: rust:1.76-bullseye
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc

pages:
  stage: publish
  image: debian:bookworm-slim
  dependencies:
    - rustdoc
  before_script:
    - apt-get update && apt-get install -y coreutils bash
    - git config --global --add safe.directory "$CI_PROJECT_DIR"
  script:
    - mkdir -p public
    - mv target/doc public/doc
  artifacts:
    paths:
      - public
  only:
    - main
