stages:
  - test
  - build
  - publish

test:
  stage: test
  image: rust
  script:
    - cargo test

rustdoc:
  stage: build
  image: rust
  script:
    - cargo doc
  artifacts:
    paths:
      - target/doc

pages:
  stage: publish
  image: alpine
  dependencies:
    - rustdoc
  script:
    - mkdir -p public
    - mv target/doc public/doc
  artifacts:
    paths:
      - public
  only:
    - main
