[package]
name = "peillute"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
clap = { version = "4.5.35", features = ["derive"] }
serde = "1.0.219"
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
