[package]
name = "peillute"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
clap = { version = "4.5.35", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
