[application]
name = "peillute"

[web.app]

# HTML title tag content
title = "peillute"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "utc.peillute"
publisher = "Peill'UTC"
